
POST http://event.con/webhook
content-type: application/json

{
      "event": "PAYMENT_RECEIVED",
      "payment": {
            "object": "payment",
            "id": "pay_9442504511992301",
            "dateCreated": "2023-04-05",
            "customer": "cus_000005205264",
            "paymentLink": null,
            "value": 39.9,
            "netValue": 37.91,
            "originalValue": null,
            "interestValue": null,
            "description": "fatura",
            "billingType": "PIX",
            "confirmedDate": "2023-04-05",
            "pixTransaction": "7ed71526-ec42-413d-8ee4-039ef35b5aa5",
            "pixQrCodeId": "00ab6199-90c4-4acb-a42c-95f8d0be450b",
            "status": "RECEIVED",
            "dueDate": "2023-04-12",
            "originalDueDate": "2023-04-12",
            "paymentDate": "2023-04-05",
            "clientPaymentDate": "2023-04-05",
            "installmentNumber": null,
            "invoiceUrl": "https://sandbox.asaas.com/i/9442504511992301",
            "invoiceNumber": "02090264",
            "externalReference": "curso@escolaondigital_642d00ca22bdc",
            "deleted": false,
            "anticipated": false,
            "anticipable": false,
            "creditDate": "2023-04-05",
            "estimatedCreditDate": "2023-04-05",
            "transactionReceiptUrl": "https://sandbox.asaas.com/comprovantes/1540719351617700",
            "nossoNumero": null,
            "bankSlipUrl": null,
            "lastInvoiceViewedDate": null,
            "lastBankSlipViewedDate": null,
            "discount": {
                  "value": 0,
                  "limitDate": null,
                  "dueDateLimitDays": 0,
                  "type": "FIXED"
            },
            "fine": {
                  "value": 0,
                  "type": "FIXED"
            },
            "interest": {
                  "value": 0,
                  "type": "PERCENTAGE"
            },
            "postalService": false,
            "refunds": null
      }
}